# For now just a simple squeleton needs proper setting for android build and tests tasks

parameters:
- name: workingDirectory
  type: string
  default: ''
- name: dependsOn
  type: string
  default:
- name: condition
  type: string
  default:

jobs:
  - job: AndroidTest
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    displayName: 'Android Tests'
    pool:
      vmImage: 'macOS'
    steps:
    - template: 'npm-steps.yml'
      parameters:
        workingDirectory: ${{ parameters.workingDirectory }}
    - task: Gradle@2
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}/**/'
        gradleWrapperFile: 'gradlew'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build test'
