parameters:
- name: token
  type: string
  default: ''

stages:
  - stage: UITestsPipelineRun
    variables:
      sauceLabsJsonString: $[ stageDependencies.EnvironmentDeploymentBuild.environment_deployment_build.outputs['deploySauceLabs.mSauceLabsAppsID'] ]
    jobs:
      - job: run_tests_pipeline
        displayName: 'Start UITests Pipeline'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: 'npm-steps.yml'
            parameters:
              workingDirectory: 'CI/templates'
          - script: 'npm run startPipeline --jsonStringBase64="$(sauceLabsJsonString)"
            workingDirectory: 'CI/templates'
            env:
              TOKEN: $(token)
